
# Configuration for Issue States - https://github.com/dessant/issue-states

# Open issues that are moved to these project columns. Set to `[]` to disable
openIssueColumns: 
  - OPEN
  - BACKLOG
  - TODAY
  - THIS WEEK
  - THIS MONTH
  - NEXT MONTH
  - NEXT QUARTER
  - "2021"
  - "2022"
  - "2030"
  - "2050"

# Close issues that are moved to these project columns. Set to `[]` to disable
closedIssueColumns:
  - DONE
  - CLOSED

# Repository to extend settings from
# _extends: repo
