
# Configuration for Issue States - https://github.com/dessant/issue-states

# Open issues that are moved to these project columns. Set to `[]` to disable
openIssueColumns: 
  - OPEN
  - BACKLOG
  - TODAY
  - THIS WEEK
  - VERSION 1
  - VERSION 2
  - VERSION 3
  - FUTURE

# Close issues that are moved to these project columns. Set to `[]` to disable
closedIssueColumns:
  - DONE
  - CLOSED

# Repository to extend settings from
# _extends: repo
