export type ProcessArtifactType =
  "string"
  | "text"
  | "ethereumAccount"
  | "inviteCredits"
  | "secretString"
  | "keyphrase"
  | "choice"
  | "number"
  | "boolean"
  | "ethereumAddress"
  | "ether"
  | "file"
  | "byteString"
