export type OmoEventTypes =
    "shell.runProcess"
  | "shell.showModal"
  | "shell.refreshView"
  | "shell.authenticated"
  | "shell.gotProfile"
  | "shell.gotSafe"
  | "shell.showNotification"
  | "process.ready"
  | "process.nop"
  | "process.back"
  | "process.shellEvent"
  | "process.continue"
  | "process.triggerSelf"
  | "process.cancel"
  | "process.prompt"
  | "process.error"
  | "process.success"
  | "process.repeat"

