/** @internal */
import { Tree, File, Link, Links, BaseLink } from '../types';
import { Skeleton, TreeInfo, FileInfo, TreeHeader, FileHeader } from '../protocol/public/types';
import { SemVer } from '../semver';
import { Metadata, UnixMeta } from '../metadata';
export declare const isFile: (obj: any) => obj is File;
export declare const isTree: (obj: any) => obj is Tree;
export declare const isBaseLink: (obj: any) => obj is BaseLink;
export declare const isLink: (obj: any) => obj is Link;
export declare const isLinks: (obj: any) => obj is Links;
export declare const isUnixMeta: (obj: any) => obj is UnixMeta;
export declare const isMetadata: (obj: any) => obj is Metadata;
export declare const isSkeleton: (obj: any) => obj is Skeleton;
export declare const isTreeHeader: (obj: any) => obj is TreeHeader;
export declare const isTreeInfo: (obj: any) => obj is TreeInfo;
export declare const isFileHeader: (obj: any) => obj is FileHeader;
export declare const isFileInfo: (obj: any) => obj is FileInfo;
export declare const isCID: (obj: any) => obj is string;
export declare const isCIDList: (obj: any) => obj is string[];
export declare const isSemVer: (obj: any) => obj is SemVer;
