export type OmoEventTypes =
    "shell.runProcess"
    | "shell.showModal"
    | "shell.openModal"
    | "shell.begin"
    | "shell.progress"
    | "shell.done"
    | "shell.navigateTo"
    | "shell.authenticated"
    | "shell.gotProfile"
    | "shell.showNotification"
    | "shell.closeModal"
    | "process.ready"
    | "process.nop"
    | "process.back"
    | "process.shellEvent"
    | "process.continue"
    | "process.triggerSelf"
    | "process.cancel"
    | "process.prompt"
    | "process.error"
    | "process.success"
    | "process.repeat"
    | "blockchain"
    | "signal.begin"
    | "signal.progress"
    | "signal.ready"
    | "signal.unavailable"

