name: Omo_Central
on: [push, pull_request]
jobs:
  prisma_job:
    name: "Omo Central"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Build
        run: ./deploy_omo_central.sh
        env:
          DO_PGSQL_CONNECTIONSTRING: ${{ secrets.DO_PGSQL_CONNECTIONSTRING }}
