name: create omo-central-server docker image
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish the docker image
        env:
          DOCKER_REGISTRY_USER: ${{secrets.DOCKER_REGISTRY_USER}}
          DOCKER_REGISTRY_PASSWORD: ${{secrets.DOCKER_REGISTRY_PASSWORD}}
        run: |
          docker login https://docker.pkg.github.com -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
          docker build . --file omo-central.Dockerfile --tag omo-central-server:latest
          docker image tag omo-central-server:latest docker.pkg.github.com/circlesland/circles-platform/omo-central-server:latest
          docker push docker.pkg.github.com/circlesland/circles-platform/omo-central-server:latest
